---
title: "Untitled"
author: "Lakshmi Batachari"
date: "July 19, 2015"
output: word_document
---
```{r, message = FALSE}
library(readxl)
library(tidyverse)
theme_set(theme_classic())
```

Import your files here:
```{r}

fileNames <- c("myData/LEB 7-19-18 Strain 34 35 36.xlsx", "myData/LEB 7-19-18 Strain 41 42 43.xlsx", "myData/LEB 7-20-18 Strain 34 35 36.xlsx", "myData/LEB 7-20-18 Strain 41 42 43.xlsx", "myData/LEB 7-25-18 Strain 41 42 43.xlsx", "myData/LEB 7-26-18 Strain 34 35 36.xlsx","myData/LEB 7-25-18 Strain 34 35 36 unsure about arabinose conc.xlsx")
processedFiles <- map(fileNames, meanExpressionOneReplicate)

combinedData <- bind_rows(processedFiles)
```

Create vectors/variables we'll need in the next step
```{r}
#set number of randomizations
sampleSize <- 10000

#create vector for the 26% RpoS level estimates
medianEstimate <- vector(length=sampleSize)

#define strain
Strain <- "LZ36"

#store mean expression values for the selected strain at 0%, 26%, and 89%
rpoS0 <- subset(combinedData, RpoS == 0 & strain == Strain, select = c(meanExpression))
rpoS26 <-subset(combinedData, RpoS == 26 & strain == Strain, select = c(meanExpression))
rpoS89 <-subset(combinedData, RpoS== 89 & strain == Strain, select = c(meanExpression))

#convert expression values into vector
rpos0Vect <- as.numeric(as.character(rpoS0$meanExpression))
rpos26Vect <- as.numeric(as.character(rpoS26$meanExpression))
rpos89Vect <- as.numeric(as.character(rpoS89$meanExpression))

#create vectors to store randomly sampled expression values at 0% and 89%
zeroPercentC <- vector(mode = "numeric", length=4)
eightyNinePercentC <- vector(mode = "numeric", length=4)
```


Now we sample from the data 10,000 times:
```{r}
#conduct resampling 10,000 times
for (i in 1:sampleSize) 
{
replicates <- sample(c(1:4), replace = TRUE, 4) #sample numbers 1-4 four times with replacement. This vector will be used to randomly pick an expression value from the vector containing all our of experimental values

#randomly samples eight expression values each at 0% and 89%
for (j in 1:4) 
{
#choose an expresion value from 0% and 89% RpoS by indexing with the number that was randomly sampled and stored in the vector 'replicates'
  
zeroPercentC[j] <- rpos0Vect[replicates[j]] 
eightyNinePercentC[j] <- rpos89Vect[replicates[j]] 

}
#determines median of expression values at the 0% and 89% level
zeroPercent <- median(zeroPercentC) 
eightyNinePercent <- median(eightyNinePercentC)

#obtains a linear fit from the median of the sampled 0% level to the median of the 89% level 
fit <- lm(c(zeroPercent, eightyNinePercent) ~ c(0, 89))

#estimates expression at the 26% RpoS level using the slope and y-intercept of the linear fit, stores estimates in vector
estimate <- 26*coef(fit)[2] + coef(fit)[1]
medianEstimate[i] <- estimate
}

#sorts 26% level estimates from lowest to highest
medianEstimate <- sort(medianEstimate)

#calculates lower and upper bounds for the 95% confidence interval of the expression at 26% RpoS 
medianEstimate[250]
medianEstimate[9750]

#calculates p-value for sensitivity by determining probability that the median 26% RpoS value will fall outside of the 95% confidence interval
if (Strain == "LB41") {
  sum(medianEstimate < median(rpos26Vect))/numberReplicates
} else {
  sum(medianEstimate > median(rpos26Vect))/numberReplicates
}

```

